name: "Build"

on: [push]
#   schedule:
#     - cron: "*/5 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.0"
      - uses: actions/setup-git@v2
        with:
          git-version: "3.1.5"
      - name: exeucte Test cases
        run: python reg.py
