name: "Build"

on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.0"
      - name: exeucte Test cases
        run: python ~/bub.py
