name: "Build"

on: [push]
#   schedule:
#     - cron: "*/5 * * * *"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.0"
      - uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: exeucte Test cases
        run: python reg.py
      - name: clone git
        run: git clone https://github.com/NiranjanLakshmi/my-app.git
